[package]
name = "culet-viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
culet-lib = { path = "../culet_lib/" }
eframe = { version = "0.25.0", features = ["wgpu"] }
egui = "0.25.0"
puffin = { version = "0.18.1", optional = true }
puffin_http = "0.15.0"
